 
---
Bot :
 token : "NjkxNDU1OTc3MjcwMTQ5MTcx.Gpi40Z.siX26xK_Jq9_KVU6AxTLmjf2EsJQ2CK_UwHJQY"
 prefix : ";"
 #Eunbi: NjkxNDU1OTc3MjcwMTQ5MTcx.Gpi40Z.siX26xK_Jq9_KVU6AxTLmjf2EsJQ2CK_UwHJQY
 #ivory: MTEzMjg2MjU0ODIwNzczMDczOQ.GsOBSo.uWyAt9uokZ6cPiCFj_JgQ_GVL1_Tjp0WX7uXi8

Version :
 ver: "Nightly 219"
 date: "2023.09.01."

Keys :
 client_id : "3D_iyIems_kMxhkrqwWE"
 client_secret : "8qhPbs_jFq"
...